### ISSUE TITLE
Python - Convert audiofile from wav to mp3: Importing WAV does not work, prints out error about ffprobe

### ISSUE THREAD

**Issue by jtiscione** [jupyter-naas/awesome-notebooks#2309]
Code segment under "Read the WAV file using pydub" does not work

Installed pydub, ffmpeg is properly added to PATH and appears in os.environ['PATH'].

This code is broken:

```
from pydub import AudioSegment
wav_audio = AudioSegment.from_file("audio.wav", format="wav")
```
**Expected behavior**
Expected pydub to load the audio file.

Instead it prints out this error:
```
... /lib/python3.11/site-packages/pydub/utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File " ... /lib/python3.11/site-packages/pydub/audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "... /lib/python3.11/site-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "... /lib/python3.11/site-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "... /lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "... /lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'ffprobe'
```

Having ffmpeg on the PATH or not makes no difference.

**Comment by jtiscione** [comment]
Never mind; I realized I have to install ffprobe also (duh) and also there is no hope for what I'm trying to do- using a prebuilt binary on a Mac with an ARM-based Silicon M1 chip is not going to work. The author of ffmpeg is [not providing a build for it](https://evermeet.cx/ffmpeg/apple-silicon-arm) and has explained why in a [screed](https://evermeet.cx/wiki/Apple%27s_disregard_for_security_and_privacy_is_mind-boggling) against Apple.
